# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mapping.xdc

# XDC: new/timing.xdc

# IP: ip/tri_mode_eth_mac_v5_5/tri_mode_eth_mac_v5_5.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tri_mode_eth_mac_v5_5 || ORIG_REF_NAME==tri_mode_eth_mac_v5_5} -quiet] -quiet
