#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Sep 18 12:08:16 CEST 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 9f6c728bcf9d4217b718b189a319391e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_mux21_behav xil_defaultlib.tb_mux21 -log elaborate.log"
xelab -wto 9f6c728bcf9d4217b718b189a319391e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_mux21_behav xil_defaultlib.tb_mux21 -log elaborate.log

